/* eslint-disable i/no-unused-modules */
import {h} from 'vue';
import {parseDom, serializeXml} from './utils.js';

const cloudfrontBaseURL = 'https://d21gfi7kzrpyzn.cloudfront.net/';
const svgs = {
  'octicon-three-bars': `${cloudfrontBaseURL}public/assets/img/svg/octicon-three-bars.svg`,
  'octicon-cloud': `${cloudfrontBaseURL}public/assets/img/svg/octicon-cloud.svg`,
  'octicon-sort-asc': `${cloudfrontBaseURL}public/assets/img/svg/octicon-sort-asc.svg`,
  'gitea-yandex': `${cloudfrontBaseURL}public/assets/img/svg/gitea-yandex.svg`,
  'octicon-duplicate': `${cloudfrontBaseURL}public/assets/img/svg/octicon-duplicate.svg`,
  'gitea-google': `${cloudfrontBaseURL}public/assets/img/svg/gitea-google.svg`,
  'octicon-alert-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-alert-fill.svg`,
  'octicon-package-dependencies': `${cloudfrontBaseURL}public/assets/img/svg/octicon-package-dependencies.svg`,
  'octicon-file': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file.svg`,
  'octicon-globe': `${cloudfrontBaseURL}public/assets/img/svg/octicon-globe.svg`,
  'gitea-azureadv2': `${cloudfrontBaseURL}public/assets/img/svg/gitea-azureadv2.svg`,
  'octicon-issue-tracked-by': `${cloudfrontBaseURL}public/assets/img/svg/octicon-issue-tracked-by.svg`,
  'octicon-file-symlink-file': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file-symlink-file.svg`,
  'octicon-mirror': `${cloudfrontBaseURL}public/assets/img/svg/octicon-mirror.svg`,
  'octicon-sign-out': `${cloudfrontBaseURL}public/assets/img/svg/octicon-sign-out.svg`,
  'octicon-pin-slash': `${cloudfrontBaseURL}public/assets/img/svg/octicon-pin-slash.svg`,
  'octicon-location': `${cloudfrontBaseURL}public/assets/img/svg/octicon-location.svg`,
  'octicon-issue-reopened': `${cloudfrontBaseURL}public/assets/img/svg/octicon-issue-reopened.svg`,
  'gitea-whitespace': `${cloudfrontBaseURL}public/assets/img/svg/gitea-whitespace.svg`,
  'octicon-file-moved': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file-moved.svg`,
  'octicon-sliders': `${cloudfrontBaseURL}public/assets/img/svg/octicon-sliders.svg`,
  'octicon-heading': `${cloudfrontBaseURL}public/assets/img/svg/octicon-heading.svg`,
  'octicon-stack': `${cloudfrontBaseURL}public/assets/img/svg/octicon-stack.svg`,
  'octicon-issue-draft': `${cloudfrontBaseURL}public/assets/img/svg/octicon-issue-draft.svg`,
  'octicon-video': `${cloudfrontBaseURL}public/assets/img/svg/octicon-video.svg`,
  'octicon-discussion-outdated': `${cloudfrontBaseURL}public/assets/img/svg/octicon-discussion-outdated.svg`,
  'gitea-onedev': `${cloudfrontBaseURL}public/assets/img/svg/gitea-onedev.svg`,
  'octicon-triangle-down': `${cloudfrontBaseURL}public/assets/img/svg/octicon-triangle-down.svg`,
  'octicon-devices': `${cloudfrontBaseURL}public/assets/img/svg/octicon-devices.svg`,
  'octicon-arrow-up': `${cloudfrontBaseURL}public/assets/img/svg/octicon-arrow-up.svg`,
  'octicon-unfold': `${cloudfrontBaseURL}public/assets/img/svg/octicon-unfold.svg`,
  'octicon-share': `${cloudfrontBaseURL}public/assets/img/svg/octicon-share.svg`,
  'octicon-rocket': `${cloudfrontBaseURL}public/assets/img/svg/octicon-rocket.svg`,
  'octicon-code-of-conduct': `${cloudfrontBaseURL}public/assets/img/svg/octicon-code-of-conduct.svg`,
  'octicon-list-unordered': `${cloudfrontBaseURL}public/assets/img/svg/octicon-list-unordered.svg`,
  'gitea-facebook': `${cloudfrontBaseURL}public/assets/img/svg/gitea-facebook.svg`,
  'octicon-dot-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-dot-fill.svg`,
  'octicon-upload': `${cloudfrontBaseURL}public/assets/img/svg/octicon-upload.svg`,
  'octicon-feed-trophy': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-trophy.svg`,
  'octicon-calendar': `${cloudfrontBaseURL}public/assets/img/svg/octicon-calendar.svg`,
  'gitea-unlock': `${cloudfrontBaseURL}public/assets/img/svg/gitea-unlock.svg`,
  'octicon-repo-clone': `${cloudfrontBaseURL}public/assets/img/svg/octicon-repo-clone.svg`,
  'octicon-person-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-person-fill.svg`,
  'octicon-briefcase': `${cloudfrontBaseURL}public/assets/img/svg/octicon-briefcase.svg`,
  'octicon-ellipsis': `${cloudfrontBaseURL}public/assets/img/svg/octicon-ellipsis.svg`,
  'octicon-clock': `${cloudfrontBaseURL}public/assets/img/svg/octicon-clock.svg`,
  'octicon-copilot': `${cloudfrontBaseURL}public/assets/img/svg/octicon-copilot.svg`,
  'octicon-tracked-by-closed-completed': `${cloudfrontBaseURL}public/assets/img/svg/octicon-tracked-by-closed-completed.svg`,
  'octicon-clock-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-clock-fill.svg`,
  'octicon-repo-template': `${cloudfrontBaseURL}public/assets/img/svg/octicon-repo-template.svg`,
  'octicon-chevron-down': `${cloudfrontBaseURL}public/assets/img/svg/octicon-chevron-down.svg`,
  'octicon-screen-full': `${cloudfrontBaseURL}public/assets/img/svg/octicon-screen-full.svg`,
  'octicon-repo-forked': `${cloudfrontBaseURL}public/assets/img/svg/octicon-repo-forked.svg`,
  'octicon-arrow-both': `${cloudfrontBaseURL}public/assets/img/svg/octicon-arrow-both.svg`,
  'octicon-filter': `${cloudfrontBaseURL}public/assets/img/svg/octicon-filter.svg`,
  'octicon-heart': `${cloudfrontBaseURL}public/assets/img/svg/octicon-heart.svg`,
  'octicon-italic': `${cloudfrontBaseURL}public/assets/img/svg/octicon-italic.svg`,
  'octicon-mortar-board': `${cloudfrontBaseURL}public/assets/img/svg/octicon-mortar-board.svg`,
  'octicon-tab-external': `${cloudfrontBaseURL}public/assets/img/svg/octicon-tab-external.svg`,
  'octicon-bookmark': `${cloudfrontBaseURL}public/assets/img/svg/octicon-bookmark.svg`,
  'octicon-codescan-checkmark': `${cloudfrontBaseURL}public/assets/img/svg/octicon-codescan-checkmark.svg`,
  'octicon-hourglass': `${cloudfrontBaseURL}public/assets/img/svg/octicon-hourglass.svg`,
  'octicon-pulse': `${cloudfrontBaseURL}public/assets/img/svg/octicon-pulse.svg`,
  'octicon-sun': `${cloudfrontBaseURL}public/assets/img/svg/octicon-sun.svg`,
  'octicon-columns': `${cloudfrontBaseURL}public/assets/img/svg/octicon-columns.svg`,
  'gitea-jetbrains': `${cloudfrontBaseURL}public/assets/img/svg/gitea-jetbrains.svg`,
  'octicon-squirrel': `${cloudfrontBaseURL}public/assets/img/svg/octicon-squirrel.svg`,
  'octicon-home': `${cloudfrontBaseURL}public/assets/img/svg/octicon-home.svg`,
  'octicon-graph': `${cloudfrontBaseURL}public/assets/img/svg/octicon-graph.svg`,
  'gitea-codebase': `${cloudfrontBaseURL}public/assets/img/svg/gitea-codebase.svg`,
  'octicon-fold': `${cloudfrontBaseURL}public/assets/img/svg/octicon-fold.svg`,
  'octicon-git-compare': `${cloudfrontBaseURL}public/assets/img/svg/octicon-git-compare.svg`,
  'octicon-feed-repo': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-repo.svg`,
  'gitea-rubygems': `${cloudfrontBaseURL}public/assets/img/svg/gitea-rubygems.svg`,
  'octicon-feed-star': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-star.svg`,
  'octicon-feed-pull-request-open': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-pull-request-open.svg`,
  'octicon-bug': `${cloudfrontBaseURL}public/assets/img/svg/octicon-bug.svg`,
  'octicon-feed-issue-closed': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-issue-closed.svg`,
  'octicon-megaphone': `${cloudfrontBaseURL}public/assets/img/svg/octicon-megaphone.svg`,
  'octicon-flame': `${cloudfrontBaseURL}public/assets/img/svg/octicon-flame.svg`,
  'octicon-skip': `${cloudfrontBaseURL}public/assets/img/svg/octicon-skip.svg`,
  'octicon-heart-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-heart-fill.svg`,
  'octicon-diff-modified': `${cloudfrontBaseURL}public/assets/img/svg/octicon-diff-modified.svg`,
  'octicon-git-commit': `${cloudfrontBaseURL}public/assets/img/svg/octicon-git-commit.svg`,
  'octicon-person-add': `${cloudfrontBaseURL}public/assets/img/svg/octicon-person-add.svg`,
  'octicon-project-symlink': `${cloudfrontBaseURL}public/assets/img/svg/octicon-project-symlink.svg`,
  'octicon-feed-issue-open': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-issue-open.svg`,
  'octicon-codescan': `${cloudfrontBaseURL}public/assets/img/svg/octicon-codescan.svg`,
  'gitea-twitter': `${cloudfrontBaseURL}public/assets/img/svg/gitea-twitter.svg`,
  'octicon-credit-card': `${cloudfrontBaseURL}public/assets/img/svg/octicon-credit-card.svg`,
  'octicon-chevron-right': `${cloudfrontBaseURL}public/assets/img/svg/octicon-chevron-right.svg`,
  'gitea-discord': `${cloudfrontBaseURL}public/assets/img/svg/gitea-discord.svg`,
  'octicon-log': `${cloudfrontBaseURL}public/assets/img/svg/octicon-log.svg`,
  'octicon-plus-circle': `${cloudfrontBaseURL}public/assets/img/svg/octicon-plus-circle.svg`,
  'octicon-bookmark-slash': `${cloudfrontBaseURL}public/assets/img/svg/octicon-bookmark-slash.svg`,
  'octicon-quote': `${cloudfrontBaseURL}public/assets/img/svg/octicon-quote.svg`,
  'octicon-unverified': `${cloudfrontBaseURL}public/assets/img/svg/octicon-unverified.svg`,
  'octicon-bold': `${cloudfrontBaseURL}public/assets/img/svg/octicon-bold.svg`,
  'gitea-vagrant': `${cloudfrontBaseURL}public/assets/img/svg/gitea-vagrant.svg`,
  'octicon-hash': `${cloudfrontBaseURL}public/assets/img/svg/octicon-hash.svg`,
  'gitea-gogs': `${cloudfrontBaseURL}public/assets/img/svg/gitea-gogs.svg`,
  'octicon-feed-issue-reopen': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-issue-reopen.svg`,
  'octicon-table': `${cloudfrontBaseURL}public/assets/img/svg/octicon-table.svg`,
  'octicon-unlink': `${cloudfrontBaseURL}public/assets/img/svg/octicon-unlink.svg`,
  'gitea-azuread': `${cloudfrontBaseURL}public/assets/img/svg/gitea-azuread.svg`,
  'octicon-logo-github': `${cloudfrontBaseURL}public/assets/img/svg/octicon-logo-github.svg`,
  'octicon-tracked-by-closed-not-planned': `${cloudfrontBaseURL}public/assets/img/svg/octicon-tracked-by-closed-not-planned.svg`,
  'octicon-plus': `${cloudfrontBaseURL}public/assets/img/svg/octicon-plus.svg`,
  'gitea-double-chevron-right': `${cloudfrontBaseURL}public/assets/img/svg/gitea-double-chevron-right.svg`,
  'octicon-dash': `${cloudfrontBaseURL}public/assets/img/svg/octicon-dash.svg`,
  'octicon-paper-airplane': `${cloudfrontBaseURL}public/assets/img/svg/octicon-paper-airplane.svg`,
  'octicon-device-camera-video': `${cloudfrontBaseURL}public/assets/img/svg/octicon-device-camera-video.svg`,
  'octicon-list-ordered': `${cloudfrontBaseURL}public/assets/img/svg/octicon-list-ordered.svg`,
  'octicon-circle-slash': `${cloudfrontBaseURL}public/assets/img/svg/octicon-circle-slash.svg`,
  'octicon-zap': `${cloudfrontBaseURL}public/assets/img/svg/octicon-zap.svg`,
  'octicon-pencil': `${cloudfrontBaseURL}public/assets/img/svg/octicon-pencil.svg`,
  'octicon-file-directory': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file-directory.svg`,
  'octicon-move-to-end': `${cloudfrontBaseURL}public/assets/img/svg/octicon-move-to-end.svg`,
  'octicon-gear': `${cloudfrontBaseURL}public/assets/img/svg/octicon-gear.svg`,
  'octicon-unlock': `${cloudfrontBaseURL}public/assets/img/svg/octicon-unlock.svg`,
  'octicon-eye': `${cloudfrontBaseURL}public/assets/img/svg/octicon-eye.svg`,
  'octicon-info': `${cloudfrontBaseURL}public/assets/img/svg/octicon-info.svg`,
  'octicon-file-binary': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file-binary.svg`,
  'octicon-project-roadmap': `${cloudfrontBaseURL}public/assets/img/svg/octicon-project-roadmap.svg`,
  'octicon-book': `${cloudfrontBaseURL}public/assets/img/svg/octicon-book.svg`,
  'octicon-x': `${cloudfrontBaseURL}public/assets/img/svg/octicon-x.svg`,
  'octicon-arrow-up-left': `${cloudfrontBaseURL}public/assets/img/svg/octicon-arrow-up-left.svg`,
  'octicon-image': `${cloudfrontBaseURL}public/assets/img/svg/octicon-image.svg`,
  'octicon-zoom-out': `${cloudfrontBaseURL}public/assets/img/svg/octicon-zoom-out.svg`,
  'octicon-bell': `${cloudfrontBaseURL}public/assets/img/svg/octicon-bell.svg`,
  'gitea-gitea': `${cloudfrontBaseURL}public/assets/img/svg/gitea-gitea.svg`,
  'octicon-plug': `${cloudfrontBaseURL}public/assets/img/svg/octicon-plug.svg`,
  'octicon-telescope-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-telescope-fill.svg`,
  'octicon-goal': `${cloudfrontBaseURL}public/assets/img/svg/octicon-goal.svg`,
  'octicon-link-external': `${cloudfrontBaseURL}public/assets/img/svg/octicon-link-external.svg`,
  'octicon-strikethrough': `${cloudfrontBaseURL}public/assets/img/svg/octicon-strikethrough.svg`,
  'octicon-feed-issue-draft': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-issue-draft.svg`,
  'octicon-kebab-horizontal': `${cloudfrontBaseURL}public/assets/img/svg/octicon-kebab-horizontal.svg`,
  'octicon-move-to-start': `${cloudfrontBaseURL}public/assets/img/svg/octicon-move-to-start.svg`,
  'octicon-code': `${cloudfrontBaseURL}public/assets/img/svg/octicon-code.svg`,
  'octicon-feed-heart': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-heart.svg`,
  'octicon-container': `${cloudfrontBaseURL}public/assets/img/svg/octicon-container.svg`,
  'octicon-milestone': `${cloudfrontBaseURL}public/assets/img/svg/octicon-milestone.svg`,
  'octicon-stop': `${cloudfrontBaseURL}public/assets/img/svg/octicon-stop.svg`,
  'octicon-issue-tracks': `${cloudfrontBaseURL}public/assets/img/svg/octicon-issue-tracks.svg`,
  'octicon-workflow': `${cloudfrontBaseURL}public/assets/img/svg/octicon-workflow.svg`,
  'octicon-discussion-duplicate': `${cloudfrontBaseURL}public/assets/img/svg/octicon-discussion-duplicate.svg`,
  'octicon-sort-desc': `${cloudfrontBaseURL}public/assets/img/svg/octicon-sort-desc.svg`,
  'octicon-report': `${cloudfrontBaseURL}public/assets/img/svg/octicon-report.svg`,
  'octicon-square': `${cloudfrontBaseURL}public/assets/img/svg/octicon-square.svg`,
  'octicon-diff': `${cloudfrontBaseURL}public/assets/img/svg/octicon-diff.svg`,
  'octicon-feed-tag': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-tag.svg`,
  'octicon-package': `${cloudfrontBaseURL}public/assets/img/svg/octicon-package.svg`,
  'octicon-triangle-right': `${cloudfrontBaseURL}public/assets/img/svg/octicon-triangle-right.svg`,
  'octicon-mail': `${cloudfrontBaseURL}public/assets/img/svg/octicon-mail.svg`,
  'octicon-arrow-switch': `${cloudfrontBaseURL}public/assets/img/svg/octicon-arrow-switch.svg`,
  'gitea-double-chevron-left': `${cloudfrontBaseURL}public/assets/img/svg/gitea-double-chevron-left.svg`,
  'octicon-stopwatch': `${cloudfrontBaseURL}public/assets/img/svg/octicon-stopwatch.svg`,
  'octicon-horizontal-rule': `${cloudfrontBaseURL}public/assets/img/svg/octicon-horizontal-rule.svg`,
  'octicon-light-bulb': `${cloudfrontBaseURL}public/assets/img/svg/octicon-light-bulb.svg`,
  'octicon-infinity': `${cloudfrontBaseURL}public/assets/img/svg/octicon-infinity.svg`,
  'octicon-apps': `${cloudfrontBaseURL}public/assets/img/svg/octicon-apps.svg`,
  'octicon-arrow-up-right': `${cloudfrontBaseURL}public/assets/img/svg/octicon-arrow-up-right.svg`,
  'octicon-codespaces': `${cloudfrontBaseURL}public/assets/img/svg/octicon-codespaces.svg`,
  'octicon-copilot-error': `${cloudfrontBaseURL}public/assets/img/svg/octicon-copilot-error.svg`,
  'octicon-note': `${cloudfrontBaseURL}public/assets/img/svg/octicon-note.svg`,
  'octicon-git-pull-request-closed': `${cloudfrontBaseURL}public/assets/img/svg/octicon-git-pull-request-closed.svg`,
  'octicon-passkey-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-passkey-fill.svg`,
  'octicon-check-circle-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-check-circle-fill.svg`,
  'gitea-go': `${cloudfrontBaseURL}public/assets/img/svg/gitea-go.svg`,
  'octicon-fold-down': `${cloudfrontBaseURL}public/assets/img/svg/octicon-fold-down.svg`,
  'octicon-lock': `${cloudfrontBaseURL}public/assets/img/svg/octicon-lock.svg`,
  'octicon-arrow-down-right': `${cloudfrontBaseURL}public/assets/img/svg/octicon-arrow-down-right.svg`,
  'octicon-checkbox': `${cloudfrontBaseURL}public/assets/img/svg/octicon-checkbox.svg`,
  'octicon-code-square': `${cloudfrontBaseURL}public/assets/img/svg/octicon-code-square.svg`,
  'octicon-people': `${cloudfrontBaseURL}public/assets/img/svg/octicon-people.svg`,
  'gitea-vscodium': `${cloudfrontBaseURL}public/assets/img/svg/gitea-vscodium.svg`,
  'octicon-paste': `${cloudfrontBaseURL}public/assets/img/svg/octicon-paste.svg`,
  'octicon-trash': `${cloudfrontBaseURL}public/assets/img/svg/octicon-trash.svg`,
  'octicon-feed-public': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-public.svg`,
  'octicon-arrow-left': `${cloudfrontBaseURL}public/assets/img/svg/octicon-arrow-left.svg`,
  'octicon-paintbrush': `${cloudfrontBaseURL}public/assets/img/svg/octicon-paintbrush.svg`,
  'fontawesome-openid': `${cloudfrontBaseURL}public/assets/img/svg/fontawesome-openid.svg`,
  'octicon-bell-slash': `${cloudfrontBaseURL}public/assets/img/svg/octicon-bell-slash.svg`,
  'octicon-link': `${cloudfrontBaseURL}public/assets/img/svg/octicon-link.svg`,
  'octicon-feed-person': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-person.svg`,
  'octicon-telescope': `${cloudfrontBaseURL}public/assets/img/svg/octicon-telescope.svg`,
  'gitea-debian': `${cloudfrontBaseURL}public/assets/img/svg/gitea-debian.svg`,
  'octicon-ruby': `${cloudfrontBaseURL}public/assets/img/svg/octicon-ruby.svg`,
  'octicon-star-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-star-fill.svg`,
  'gitea-composer': `${cloudfrontBaseURL}public/assets/img/svg/gitea-composer.svg`,
  'octicon-feed-forked': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-forked.svg`,
  'octicon-archive': `${cloudfrontBaseURL}public/assets/img/svg/octicon-archive.svg`,
  'octicon-sponsor-tiers': `${cloudfrontBaseURL}public/assets/img/svg/octicon-sponsor-tiers.svg`,
  'octicon-repo-deleted': `${cloudfrontBaseURL}public/assets/img/svg/octicon-repo-deleted.svg`,
  'octicon-move-to-bottom': `${cloudfrontBaseURL}public/assets/img/svg/octicon-move-to-bottom.svg`,
  'gitea-gitlab': `${cloudfrontBaseURL}public/assets/img/svg/gitea-gitlab.svg`,
  'gitea-openid': `${cloudfrontBaseURL}public/assets/img/svg/gitea-openid.svg`,
  'octicon-feed-rocket': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-rocket.svg`,
  'gitea-maven': `${cloudfrontBaseURL}public/assets/img/svg/gitea-maven.svg`,
  'octicon-question': `${cloudfrontBaseURL}public/assets/img/svg/octicon-question.svg`,
  'octicon-thumbsup': `${cloudfrontBaseURL}public/assets/img/svg/octicon-thumbsup.svg`,
  'octicon-feed-pull-request-draft': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-pull-request-draft.svg`,
  'octicon-single-select': `${cloudfrontBaseURL}public/assets/img/svg/octicon-single-select.svg`,
  'octicon-trophy': `${cloudfrontBaseURL}public/assets/img/svg/octicon-trophy.svg`,
  'octicon-device-camera': `${cloudfrontBaseURL}public/assets/img/svg/octicon-device-camera.svg`,
  'octicon-accessibility': `${cloudfrontBaseURL}public/assets/img/svg/octicon-accessibility.svg`,
  'gitea-cran': `${cloudfrontBaseURL}public/assets/img/svg/gitea-cran.svg`,
  'octicon-repo-push': `${cloudfrontBaseURL}public/assets/img/svg/octicon-repo-push.svg`,
  'gitea-chef': `${cloudfrontBaseURL}public/assets/img/svg/gitea-chef.svg`,
  'octicon-hubot': `${cloudfrontBaseURL}public/assets/img/svg/octicon-hubot.svg`,
  'gitea-helm': `${cloudfrontBaseURL}public/assets/img/svg/gitea-helm.svg`,
  'octicon-typography': `${cloudfrontBaseURL}public/assets/img/svg/octicon-typography.svg`,
  'octicon-file-submodule': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file-submodule.svg`,
  'octicon-package-dependents': `${cloudfrontBaseURL}public/assets/img/svg/octicon-package-dependents.svg`,
  'octicon-skip-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-skip-fill.svg`,
  'octicon-north-star': `${cloudfrontBaseURL}public/assets/img/svg/octicon-north-star.svg`,
  'octicon-file-directory-symlink': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file-directory-symlink.svg`,
  'octicon-chevron-up': `${cloudfrontBaseURL}public/assets/img/svg/octicon-chevron-up.svg`,
  'octicon-mute': `${cloudfrontBaseURL}public/assets/img/svg/octicon-mute.svg`,
  'fontawesome-windows': `${cloudfrontBaseURL}public/assets/img/svg/fontawesome-windows.svg`,
  'octicon-desktop-download': `${cloudfrontBaseURL}public/assets/img/svg/octicon-desktop-download.svg`,
  'octicon-shield-lock': `${cloudfrontBaseURL}public/assets/img/svg/octicon-shield-lock.svg`,
  'octicon-download': `${cloudfrontBaseURL}public/assets/img/svg/octicon-download.svg`,
  'octicon-browser': `${cloudfrontBaseURL}public/assets/img/svg/octicon-browser.svg`,
  'octicon-checklist': `${cloudfrontBaseURL}public/assets/img/svg/octicon-checklist.svg`,
  'gitea-pub': `${cloudfrontBaseURL}public/assets/img/svg/gitea-pub.svg`,
  'octicon-repo': `${cloudfrontBaseURL}public/assets/img/svg/octicon-repo.svg`,
  'octicon-star': `${cloudfrontBaseURL}public/assets/img/svg/octicon-star.svg`,
  'gitea-vscode': `${cloudfrontBaseURL}public/assets/img/svg/gitea-vscode.svg`,
  'octicon-number': `${cloudfrontBaseURL}public/assets/img/svg/octicon-number.svg`,
  'octicon-shield-x': `${cloudfrontBaseURL}public/assets/img/svg/octicon-shield-x.svg`,
  'octicon-smiley': `${cloudfrontBaseURL}public/assets/img/svg/octicon-smiley.svg`,
  'octicon-play': `${cloudfrontBaseURL}public/assets/img/svg/octicon-play.svg`,
  'octicon-broadcast': `${cloudfrontBaseURL}public/assets/img/svg/octicon-broadcast.svg`,
  'octicon-paperclip': `${cloudfrontBaseURL}public/assets/img/svg/octicon-paperclip.svg`,
  'octicon-thumbsdown': `${cloudfrontBaseURL}public/assets/img/svg/octicon-thumbsdown.svg`,
  'octicon-diff-ignored': `${cloudfrontBaseURL}public/assets/img/svg/octicon-diff-ignored.svg`,
  'octicon-server': `${cloudfrontBaseURL}public/assets/img/svg/octicon-server.svg`,
  'octicon-check': `${cloudfrontBaseURL}public/assets/img/svg/octicon-check.svg`,
  'octicon-arrow-down': `${cloudfrontBaseURL}public/assets/img/svg/octicon-arrow-down.svg`,
  'octicon-tag': `${cloudfrontBaseURL}public/assets/img/svg/octicon-tag.svg`,
  'octicon-diff-removed': `${cloudfrontBaseURL}public/assets/img/svg/octicon-diff-removed.svg`,
  'octicon-shield': `${cloudfrontBaseURL}public/assets/img/svg/octicon-shield.svg`,
  'gitea-conda': `${cloudfrontBaseURL}public/assets/img/svg/gitea-conda.svg`,
  'octicon-cloud-offline': `${cloudfrontBaseURL}public/assets/img/svg/octicon-cloud-offline.svg`,
  'octicon-redo': `${cloudfrontBaseURL}public/assets/img/svg/octicon-redo.svg`,
  'octicon-zoom-in': `${cloudfrontBaseURL}public/assets/img/svg/octicon-zoom-in.svg`,
  'octicon-git-merge-queue': `${cloudfrontBaseURL}public/assets/img/svg/octicon-git-merge-queue.svg`,
  'octicon-markdown': `${cloudfrontBaseURL}public/assets/img/svg/octicon-markdown.svg`,
  'gitea-matrix': `${cloudfrontBaseURL}public/assets/img/svg/gitea-matrix.svg`,
  'octicon-unmute': `${cloudfrontBaseURL}public/assets/img/svg/octicon-unmute.svg`,
  'gitea-npm': `${cloudfrontBaseURL}public/assets/img/svg/gitea-npm.svg`,
  'gitea-split': `${cloudfrontBaseURL}public/assets/img/svg/gitea-split.svg`,
  'octicon-file-added': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file-added.svg`,
  'octicon-organization': `${cloudfrontBaseURL}public/assets/img/svg/octicon-organization.svg`,
  'octicon-copilot-warning': `${cloudfrontBaseURL}public/assets/img/svg/octicon-copilot-warning.svg`,
  'gitea-empty-checkbox': `${cloudfrontBaseURL}public/assets/img/svg/gitea-empty-checkbox.svg`,
  'octicon-git-merge': `${cloudfrontBaseURL}public/assets/img/svg/octicon-git-merge.svg`,
  'octicon-copy': `${cloudfrontBaseURL}public/assets/img/svg/octicon-copy.svg`,
  'octicon-check-circle': `${cloudfrontBaseURL}public/assets/img/svg/octicon-check-circle.svg`,
  'octicon-feed-pull-request-closed': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-pull-request-closed.svg`,
  'material-invert-colors': `${cloudfrontBaseURL}public/assets/img/svg/material-invert-colors.svg`,
  'octicon-beaker': `${cloudfrontBaseURL}public/assets/img/svg/octicon-beaker.svg`,
  'octicon-move-to-top': `${cloudfrontBaseURL}public/assets/img/svg/octicon-move-to-top.svg`,
  'octicon-file-directory-open-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file-directory-open-fill.svg`,
  'octicon-git-pull-request-draft': `${cloudfrontBaseURL}public/assets/img/svg/octicon-git-pull-request-draft.svg`,
  'octicon-grabber': `${cloudfrontBaseURL}public/assets/img/svg/octicon-grabber.svg`,
  'octicon-versions': `${cloudfrontBaseURL}public/assets/img/svg/octicon-versions.svg`,
  'octicon-webhook': `${cloudfrontBaseURL}public/assets/img/svg/octicon-webhook.svg`,
  'octicon-chevron-left': `${cloudfrontBaseURL}public/assets/img/svg/octicon-chevron-left.svg`,
  'octicon-pivot-column': `${cloudfrontBaseURL}public/assets/img/svg/octicon-pivot-column.svg`,
  'gitea-rpm': `${cloudfrontBaseURL}public/assets/img/svg/gitea-rpm.svg`,
  'octicon-dot': `${cloudfrontBaseURL}public/assets/img/svg/octicon-dot.svg`,
  'octicon-rel-file-path': `${cloudfrontBaseURL}public/assets/img/svg/octicon-rel-file-path.svg`,
  'octicon-sidebar-expand': `${cloudfrontBaseURL}public/assets/img/svg/octicon-sidebar-expand.svg`,
  'octicon-discussion-closed': `${cloudfrontBaseURL}public/assets/img/svg/octicon-discussion-closed.svg`,
  'gitea-lock-cog': `${cloudfrontBaseURL}public/assets/img/svg/gitea-lock-cog.svg`,
  'octicon-file-directory-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file-directory-fill.svg`,
  'gitea-mastodon': `${cloudfrontBaseURL}public/assets/img/svg/gitea-mastodon.svg`,
  'octicon-arrow-right': `${cloudfrontBaseURL}public/assets/img/svg/octicon-arrow-right.svg`,
  'octicon-mention': `${cloudfrontBaseURL}public/assets/img/svg/octicon-mention.svg`,
  'octicon-square-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-square-fill.svg`,
  'octicon-issue-opened': `${cloudfrontBaseURL}public/assets/img/svg/octicon-issue-opened.svg`,
  'octicon-git-branch': `${cloudfrontBaseURL}public/assets/img/svg/octicon-git-branch.svg`,
  'octicon-diff-renamed': `${cloudfrontBaseURL}public/assets/img/svg/octicon-diff-renamed.svg`,
  'octicon-reply': `${cloudfrontBaseURL}public/assets/img/svg/octicon-reply.svg`,
  'octicon-repo-locked': `${cloudfrontBaseURL}public/assets/img/svg/octicon-repo-locked.svg`,
  'gitea-nextcloud': `${cloudfrontBaseURL}public/assets/img/svg/gitea-nextcloud.svg`,
  'octicon-shield-check': `${cloudfrontBaseURL}public/assets/img/svg/octicon-shield-check.svg`,
  'octicon-moon': `${cloudfrontBaseURL}public/assets/img/svg/octicon-moon.svg`,
  'octicon-law': `${cloudfrontBaseURL}public/assets/img/svg/octicon-law.svg`,
  'octicon-share-android': `${cloudfrontBaseURL}public/assets/img/svg/octicon-share-android.svg`,
  'octicon-key': `${cloudfrontBaseURL}public/assets/img/svg/octicon-key.svg`,
  'octicon-file-zip': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file-zip.svg`,
  'octicon-device-desktop': `${cloudfrontBaseURL}public/assets/img/svg/octicon-device-desktop.svg`,
  'octicon-fold-up': `${cloudfrontBaseURL}public/assets/img/svg/octicon-fold-up.svg`,
  'octicon-multi-select': `${cloudfrontBaseURL}public/assets/img/svg/octicon-multi-select.svg`,
  'octicon-device-mobile': `${cloudfrontBaseURL}public/assets/img/svg/octicon-device-mobile.svg`,
  'octicon-tools': `${cloudfrontBaseURL}public/assets/img/svg/octicon-tools.svg`,
  'octicon-triangle-left': `${cloudfrontBaseURL}public/assets/img/svg/octicon-triangle-left.svg`,
  'gitea-join': `${cloudfrontBaseURL}public/assets/img/svg/gitea-join.svg`,
  'octicon-read': `${cloudfrontBaseURL}public/assets/img/svg/octicon-read.svg`,
  'gitea-git': `${cloudfrontBaseURL}public/assets/img/svg/gitea-git.svg`,
  'octicon-file-badge': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file-badge.svg`,
  'octicon-file-diff': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file-diff.svg`,
  'gitea-alpine': `${cloudfrontBaseURL}public/assets/img/svg/gitea-alpine.svg`,
  'octicon-issue-closed': `${cloudfrontBaseURL}public/assets/img/svg/octicon-issue-closed.svg`,
  'octicon-key-asterisk': `${cloudfrontBaseURL}public/assets/img/svg/octicon-key-asterisk.svg`,
  'octicon-feed-merged': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-merged.svg`,
  'gitea-bitbucket': `${cloudfrontBaseURL}public/assets/img/svg/gitea-bitbucket.svg`,
  'octicon-meter': `${cloudfrontBaseURL}public/assets/img/svg/octicon-meter.svg`,
  'octicon-logo-gist': `${cloudfrontBaseURL}public/assets/img/svg/octicon-logo-gist.svg`,
  'octicon-id-badge': `${cloudfrontBaseURL}public/assets/img/svg/octicon-id-badge.svg`,
  'material-palette': `${cloudfrontBaseURL}public/assets/img/svg/material-palette.svg`,
  'octicon-x-circle': `${cloudfrontBaseURL}public/assets/img/svg/octicon-x-circle.svg`,
  'octicon-file-removed': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file-removed.svg`,
  'octicon-code-review': `${cloudfrontBaseURL}public/assets/img/svg/octicon-code-review.svg`,
  'octicon-shield-slash': `${cloudfrontBaseURL}public/assets/img/svg/octicon-shield-slash.svg`,
  'octicon-history': `${cloudfrontBaseURL}public/assets/img/svg/octicon-history.svg`,
  'octicon-project': `${cloudfrontBaseURL}public/assets/img/svg/octicon-project.svg`,
  'octicon-iterations': `${cloudfrontBaseURL}public/assets/img/svg/octicon-iterations.svg`,
  'octicon-x-circle-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-x-circle-fill.svg`,
  'octicon-sparkle-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-sparkle-fill.svg`,
  'octicon-pin': `${cloudfrontBaseURL}public/assets/img/svg/octicon-pin.svg`,
  'octicon-cross-reference': `${cloudfrontBaseURL}public/assets/img/svg/octicon-cross-reference.svg`,
  'octicon-screen-normal': `${cloudfrontBaseURL}public/assets/img/svg/octicon-screen-normal.svg`,
  'octicon-undo': `${cloudfrontBaseURL}public/assets/img/svg/octicon-undo.svg`,
  'gitea-gitbucket': `${cloudfrontBaseURL}public/assets/img/svg/gitea-gitbucket.svg`,
  'octicon-filter-remove': `${cloudfrontBaseURL}public/assets/img/svg/octicon-filter-remove.svg`,
  'fontawesome-save': `${cloudfrontBaseURL}public/assets/img/svg/fontawesome-save.svg`,
  'octicon-dependabot': `${cloudfrontBaseURL}public/assets/img/svg/octicon-dependabot.svg`,
  'gitea-exclamation': `${cloudfrontBaseURL}public/assets/img/svg/gitea-exclamation.svg`,
  'octicon-mark-github': `${cloudfrontBaseURL}public/assets/img/svg/octicon-mark-github.svg`,
  'octicon-diamond': `${cloudfrontBaseURL}public/assets/img/svg/octicon-diamond.svg`,
  'octicon-file-code': `${cloudfrontBaseURL}public/assets/img/svg/octicon-file-code.svg`,
  'octicon-circle': `${cloudfrontBaseURL}public/assets/img/svg/octicon-circle.svg`,
  'octicon-triangle-up': `${cloudfrontBaseURL}public/assets/img/svg/octicon-triangle-up.svg`,
  'octicon-person': `${cloudfrontBaseURL}public/assets/img/svg/octicon-person.svg`,
  'octicon-bell-fill': `${cloudfrontBaseURL}public/assets/img/svg/octicon-bell-fill.svg`,
  'gitea-conan': `${cloudfrontBaseURL}public/assets/img/svg/gitea-conan.svg`,
  'octicon-eye-closed': `${cloudfrontBaseURL}public/assets/img/svg/octicon-eye-closed.svg`,
  'octicon-inbox': `${cloudfrontBaseURL}public/assets/img/svg/octicon-inbox.svg`,
  'octicon-cache': `${cloudfrontBaseURL}public/assets/img/svg/octicon-cache.svg`,
  'octicon-blocked': `${cloudfrontBaseURL}public/assets/img/svg/octicon-blocked.svg`,
  'octicon-unread': `${cloudfrontBaseURL}public/assets/img/svg/octicon-unread.svg`,
  'gitea-cargo': `${cloudfrontBaseURL}public/assets/img/svg/gitea-cargo.svg`,
  'octicon-verified': `${cloudfrontBaseURL}public/assets/img/svg/octicon-verified.svg`,
  'octicon-tasklist': `${cloudfrontBaseURL}public/assets/img/svg/octicon-tasklist.svg`,
  'octicon-database': `${cloudfrontBaseURL}public/assets/img/svg/octicon-database.svg`,
  'octicon-diff-added': `${cloudfrontBaseURL}public/assets/img/svg/octicon-diff-added.svg`,
  'fontawesome-send': `${cloudfrontBaseURL}public/assets/img/svg/fontawesome-send.svg`,
  'octicon-sync': `${cloudfrontBaseURL}public/assets/img/svg/octicon-sync.svg`,
  'octicon-rows': `${cloudfrontBaseURL}public/assets/img/svg/octicon-rows.svg`,
  'octicon-command-palette': `${cloudfrontBaseURL}public/assets/img/svg/octicon-command-palette.svg`,
  'octicon-project-template': `${cloudfrontBaseURL}public/assets/img/svg/octicon-project-template.svg`,
  'octicon-sidebar-collapse': `${cloudfrontBaseURL}public/assets/img/svg/octicon-sidebar-collapse.svg`,
  'gitea-microsoftonline': `${cloudfrontBaseURL}public/assets/img/svg/gitea-microsoftonline.svg`,
  'octicon-feed-plus': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-plus.svg`,
  'octicon-search': `${cloudfrontBaseURL}public/assets/img/svg/octicon-search.svg`,
  'octicon-cpu': `${cloudfrontBaseURL}public/assets/img/svg/octicon-cpu.svg`,
  'octicon-sign-in': `${cloudfrontBaseURL}public/assets/img/svg/octicon-sign-in.svg`,
  'octicon-no-entry': `${cloudfrontBaseURL}public/assets/img/svg/octicon-no-entry.svg`,
  'gitea-python': `${cloudfrontBaseURL}public/assets/img/svg/gitea-python.svg`,
  'gitea-lock': `${cloudfrontBaseURL}public/assets/img/svg/gitea-lock.svg`,
  'octicon-comment-discussion': `${cloudfrontBaseURL}public/assets/img/svg/octicon-comment-discussion.svg`,
  'octicon-arrow-down-left': `${cloudfrontBaseURL}public/assets/img/svg/octicon-arrow-down-left.svg`,
  'gitea-nuget': `${cloudfrontBaseURL}public/assets/img/svg/gitea-nuget.svg`,
  'octicon-git-pull-request': `${cloudfrontBaseURL}public/assets/img/svg/octicon-git-pull-request.svg`,
  'octicon-fiscal-host': `${cloudfrontBaseURL}public/assets/img/svg/octicon-fiscal-host.svg`,
  'octicon-terminal': `${cloudfrontBaseURL}public/assets/img/svg/octicon-terminal.svg`,
  'octicon-repo-pull': `${cloudfrontBaseURL}public/assets/img/svg/octicon-repo-pull.svg`,
  'gitea-dropbox': `${cloudfrontBaseURL}public/assets/img/svg/gitea-dropbox.svg`,
  'octicon-feed-discussion': `${cloudfrontBaseURL}public/assets/img/svg/octicon-feed-discussion.svg`,
  'gitea-swift': `${cloudfrontBaseURL}public/assets/img/svg/gitea-swift.svg`,
  'octicon-accessibility-inset': `${cloudfrontBaseURL}public/assets/img/svg/octicon-accessibility-inset.svg`,
  'octicon-alert': `${cloudfrontBaseURL}public/assets/img/svg/octicon-alert.svg`,
  'octicon-gift': `${cloudfrontBaseURL}public/assets/img/svg/octicon-gift.svg`,
  'octicon-comment': `${cloudfrontBaseURL}public/assets/img/svg/octicon-comment.svg`,
  'octicon-rss': `${cloudfrontBaseURL}public/assets/img/svg/octicon-rss.svg`,
};

// TODO: use a more general approach to access SVG icons.
//  At the moment, developers must check, pick and fill the names manually,
//  most of the SVG icons in assets couldn't be used directly.

// retrieve an HTML string for given SVG icon name, size and additional classes

export function svg(name, size = 16, className = '') {
  if (!(name in svgs)) {
    throw new Error(`Unknown SVG icon: ${name}`);
  }

  // SVG 파일 URL을 가져옴
  const svgUrl = svgs[name];

  // 이미지 태그를 만들어서 반환
  const img = document.createElement('img');
  img.src = svgUrl;
  img.setAttribute('width', String(size));
  img.setAttribute('height', String(size));

  img.classList.add('svg', name);

  if (className) {
    img.classList.add(...className.split(/\s+/).filter(Boolean));
  }

  return img.outerHTML;
}

export function svgParseOuterInner(name) {
  const svgStr = svgs[name];
  if (!svgStr) throw new Error(`Unknown SVG icon: ${name}`);

  const p1 = svgStr.indexOf('>'), p2 = svgStr.lastIndexOf('<');
  if (p1 === -1 || p2 === -1) throw new Error(`Invalid SVG icon: ${name}`);
  const svgInnerHtml = svgStr.slice(p1 + 1, p2);
  const svgOuterHtml = svgStr.slice(0, p1 + 1) + svgStr.slice(p2);
  const svgDoc = parseDom(svgOuterHtml, 'image/svg+xml');
  const svgOuter = svgDoc.firstChild;
  return {svgOuter, svgInnerHtml};
}

export const SvgIcon = {
  name: 'SvgIcon',
  props: {
    name: {type: String, required: true},
    size: {type: Number, default: 16},
    className: {type: String, default: ''},
  },
  render() {
    if (!(this.name in svgs)) {
      throw new Error(`Unknown SVG icon: ${this.name}`);
    }

    const svgUrl = svgs[this.name];
    const imgAttrs = {
      src: svgUrl,
      width: this.size,
      height: this.size,
      class: this.className,
    };

    return h('img', {
      ...imgAttrs,
    });
  },
};
